title: Full of Symmetries
author: Diego Lopez
description: >- 
        Diego Lopez's personal website
baseurl: "" 
url: "https://symmetries.github.io" 
github_username: Symmetries

markdown: kramdown
theme: minima

collections:
        projects:
                output: true
                permalink: /:collection/:name
